name: Deploy EKS Cluster with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy-base:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./base

    steps:
    # 1. Checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar o AWS CLI
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SECRET_ACCESS_TOKEN }}
        aws-region: ${{ vars.AWS_REGION }}

    # 3. Configurar o Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7 # Ajuste para a versão do Terraform utilizada

    # 4. Inicializar o Terraform
    - name: Terraform Init
      run: terraform init -backend-config="bucket=${{ vars.BACKEND_BUCKET_NAME }}" -backend-config="key=microsservices/terraform.tfstate" -backend-config="region=${{ vars.AWS_REGION }}"

    # 5. Validar o Terraform
    - name: Terraform Validate
      run: terraform validate

    # 6. Gerar o plano do Terraform
    - name: Terraform Plan
      run: terraform plan -out=tfplan -var="regionDefault=${{ vars.AWS_REGION }}" -var="accountIdVoclabs=${{ secrets.AWS_ACCOUNT_ID_VOCLABS }}" -var="projectName=${{ vars.PROJECT_NAME }}"  -var="s3BucketVideosName=${{vars.VIDEOS_BUCKET_NAME}}" -var="sqsVideoStatusQueueName=${{vars.VIDEOS_STATUS_SQS_NAME}}"

    # 7. Aplicar o plano do Terraform
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan

    # 8. Configurar o Kubectl
    - name: Install Kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
    - name: Configure Kubectl
      run: |
        aws eks --region ${{ vars.AWS_REGION }} update-kubeconfig --name ${{ vars.PROJECT_NAME }}

    # 9. Implantar servidor de metricas para o cluster
    - name: Deploy Metrics Server
      run: kubectl apply -f ../k8s/metrics-server.yaml
