name: sonarqube

on:
  pull_request:
    branches: [ "main" ]

jobs:
  sonar-analysis:
    name: Analyze SnackTech
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Runs SonarQube Scanner
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}