name: sonarqube

on:
  pull_request:
    branches: [ "main" ]

jobs:
  sonar-analysis:
    name: Analyze SnackTech
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install SonarScanner
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.projectKey=SnackTechTeam_snapvid-infra
            -Dsonar.organization=snacktechteam
            -Dsonar.host.url="https://sonarcloud.io"
            -Dsonar.branch.name=${{ github.ref_name }}
            -Dsonar.projectName=SnackTechTeam_snapvid-infra